#!/usr/bin/env bash

# Vraag om de gebruikersnaam, gebruik de huidige gebruikersnaam als standaard
read -p "Geef je naam (standaard: $(whoami)): " username
username=${username:-$(whoami)}

# Vraag om het wachtwoord en herhaal dit tot tweemaal hetzelfde wachtwoord wordt ingevoerd
while true; do
    read -s -p "Voer je wachtwoord in (minimaal 8 karakters): " password
    echo
    read -s -p "Herhaal je wachtwoord: " password_confirm
    echo
    if [ "$password" == "$password_confirm" ] && [ ${#password} -ge 8 ]; then
        break
    else
        echo "Wachtwoorden komen niet overeen of zijn te kort. Probeer opnieuw."
    fi
done

# Genereer de MD5-hash van het wachtwoord
password_hash=$(echo -n "$password" | md5sum | cut -d' ' -f1)

# Schrijf de gebruikersnaam en de MD5-hash naar het tekstbestand
echo "Gebruikersnaam: $username" > "$1"
echo "Wachtwoord hash: $password_hash" >> "$1"

echo "Login aangemaakt en opgeslagen in $1."