#!/usr/bin/env bash
cd ./EOS1_bestanden

for file in *.jpg
do
	mv "$file" "${file%.jpg}.png"
done

for file in *.gif
do
	mv "$file" "${file%.gif}.png"
done

mogrify -resize '128x128' *.png

for file in *.png~
do
	rm $file
done

